services:
  personal-website:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lab12-personal-website
    ports:
      - "8081:80"
    restart: unless-stopped

  todo-app:
    build:
      context: .
      dockerfile: todo.Dockerfile
    container_name: lab12-todo-app
    ports:
      - "8082:80"
    restart: unless-stopped
